id: ef447e5cd5874e2a9c5322a978b94376
initial_creation_type: ocr
source_metadata:
  volumes:
    670a3a86e7ba47028e8344e9b436e000:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
